<robot>

    <xacro:property name = "Base_width" value = "0.25"/>
    <xacro:property name = "Base_depth" value = "0.25"/>
    <xacro:property name = "Base_height" value = "0.2"/>
    <xacro:property name = "Wheel_radius" value = "0.2"/>
    <xacro:property name = "wheel_support_radius" value = "0.1"/>
    <xacro:property name = "wheel_joint_offset" value = "0.03"/>
    <xacro:property name = "wheel_gap" value = "0.006"/>
    <xacro:property name ="support_wheel_radius" value="${wheel_radius/2}"/>
    <xacro:property name ="support_wheel_joint_offset" value="-0.052"/>

</robot>